USE mysql;

CREATE DATABASE IF NOT EXISTS mw;

GRANT ALL PRIVILEGES ON mw.* TO mw@localhost IDENTIFIED BY 'a1b2c3d4';
GRANT ALL PRIVILEGES ON mw.* TO mw@localhost.localdomain IDENTIFIED BY 'a1b2c3d4';
GRANT ALL PRIVILEGES ON mw.* TO mw@'%' IDENTIFIED BY 'a1b2c3d4';
