SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';


-- -----------------------------------------------------
-- Table `MWC_DOMAIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MWC_DOMAIN` ;

CREATE  TABLE IF NOT EXISTS `MWC_DOMAIN` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(45) NOT NULL ,
  `URL` VARCHAR(200) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `UK1_DOMAIN` ON `MWC_DOMAIN` (`NAME` ASC) ;


-- -----------------------------------------------------
-- Table `MWC_CLIENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MWC_CLIENT` ;

CREATE  TABLE IF NOT EXISTS `MWC_CLIENT` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `USERID` VARCHAR(45) NOT NULL ,
  `PASSWORD` VARCHAR(100) NOT NULL ,
  `LAST_NAME` VARCHAR(45) NOT NULL ,
  `FIRST_NAME` VARCHAR(45) NOT NULL ,
  `EMAIL` VARCHAR(45) NOT NULL ,
  `ADDITIONAL_INFO` VARCHAR(500) NULL ,
  `PHONE_1` VARCHAR(25) NULL ,
  `PHONE_2` VARCHAR(25) NULL ,
  `STREET_ADDRESS_1` VARCHAR(200) NULL ,
  `STREET_ADDRESS_2` VARCHAR(200) NULL ,
  `CITY` VARCHAR(100) NULL ,
  `STATE` VARCHAR(50) NULL ,
  `COUNTRY` VARCHAR(50) NULL ,
  `POSTAL_CODE` VARCHAR(20) NULL ,
  `DEFAULT_DOMAIN_ID` BIGINT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK1_CLIENT`
    FOREIGN KEY (`DEFAULT_DOMAIN_ID` )
    REFERENCES `MWC_DOMAIN` (`ID` )
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `EMAIL_UNIQUE` ON `MWC_CLIENT` (`EMAIL` ASC) ;

CREATE UNIQUE INDEX `USERID_UNIQUE` ON `MWC_CLIENT` (`USERID` ASC) ;

CREATE INDEX `IDX1_CLIENT` ON `MWC_CLIENT` (`DEFAULT_DOMAIN_ID` ASC) ;


-- -----------------------------------------------------
-- Table `MWC_CLIENT_DOMAIN_MAP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MWC_CLIENT_DOMAIN_MAP` ;

CREATE  TABLE IF NOT EXISTS `MWC_CLIENT_DOMAIN_MAP` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `CLIENT_ID` BIGINT NOT NULL ,
  `DOMAIN_ID` BIGINT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK1_CLIENT_DOMAIN_MAP`
    FOREIGN KEY (`CLIENT_ID` )
    REFERENCES `MWC_CLIENT` (`ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK2_CLIENT_DOMAIN_MAP`
    FOREIGN KEY (`DOMAIN_ID` )
    REFERENCES `MWC_DOMAIN` (`ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `IDX1_CLIENT_DOMAIN_MAP` ON `MWC_CLIENT_DOMAIN_MAP` (`CLIENT_ID` ASC) ;

CREATE INDEX `IDX2_CLIENT_DOMAIN_MAP` ON `MWC_CLIENT_DOMAIN_MAP` (`DOMAIN_ID` ASC) ;

CREATE UNIQUE INDEX `UK1_CLIENT_DOMAIN_MAP` ON `MWC_CLIENT_DOMAIN_MAP` (`CLIENT_ID` ASC, `DOMAIN_ID` ASC) ;


-- -----------------------------------------------------
-- Table `MWC_ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MWC_ROLE` ;

CREATE  TABLE IF NOT EXISTS `MWC_ROLE` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(45) NOT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;

CREATE UNIQUE INDEX `UK1_ROLE` ON `MWC_ROLE` (`NAME` ASC) ;


-- -----------------------------------------------------
-- Table `MWC_CLIENT_DOMAIN_ROLE_MAP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MWC_CLIENT_DOMAIN_ROLE_MAP` ;

CREATE  TABLE IF NOT EXISTS `MWC_CLIENT_DOMAIN_ROLE_MAP` (
  `CLIENT_DOMAIN_ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `ROLE_ID` BIGINT NOT NULL ,
  PRIMARY KEY (`CLIENT_DOMAIN_ID`, `ROLE_ID`) ,
  CONSTRAINT `FK1_CLIENT_DOMAIN_ROLE_MAP`
    FOREIGN KEY (`CLIENT_DOMAIN_ID` )
    REFERENCES `MWC_CLIENT_DOMAIN_MAP` (`ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `FK2_CLIENT_DOMAIN_ROLE_MAP`
    FOREIGN KEY (`ROLE_ID` )
    REFERENCES `MWC_ROLE` (`ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `IDX1_CLIENT_DOMAIN_ROLE_MAP` ON `MWC_CLIENT_DOMAIN_ROLE_MAP` (`CLIENT_DOMAIN_ID` ASC) ;

CREATE INDEX `IDX2_CLIENT_DOMAIN_ROLE_MAP` ON `MWC_CLIENT_DOMAIN_ROLE_MAP` (`ROLE_ID` ASC) ;


-- -----------------------------------------------------
-- Table `MWC_CLIENT_PROPERTY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MWC_CLIENT_PROPERTY` ;

CREATE  TABLE IF NOT EXISTS `MWC_CLIENT_PROPERTY` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `CLIENT_ID` BIGINT NOT NULL ,
  `KEY` VARCHAR(45) NOT NULL ,
  `VALUE` VARCHAR(200) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK1_CLIENT_PROPERTY`
    FOREIGN KEY (`CLIENT_ID` )
    REFERENCES `MWC_CLIENT` (`ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `UK1_CLIENT_PROPERTY` ON `MWC_CLIENT_PROPERTY` (`CLIENT_ID` ASC, `KEY` ASC) ;

CREATE INDEX `IDX1_CLIENT_PROPERTY` ON `MWC_CLIENT_PROPERTY` (`CLIENT_ID` ASC) ;


-- -----------------------------------------------------
-- Table `MWC_DOMAIN_PROPERTY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MWC_DOMAIN_PROPERTY` ;

CREATE  TABLE IF NOT EXISTS `MWC_DOMAIN_PROPERTY` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `DOMAIN_ID` BIGINT NOT NULL ,
  `KEY` VARCHAR(45) NOT NULL ,
  `VALUE` VARCHAR(200) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK1_DOMAIN_PROPERTY`
    FOREIGN KEY (`DOMAIN_ID` )
    REFERENCES `MWC_DOMAIN` (`ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `UK1_DOMAIN_PROPERTY` ON `MWC_DOMAIN_PROPERTY` (`DOMAIN_ID` ASC, `KEY` ASC) ;

CREATE INDEX `IDX1_DOMAIN_PROPERTTY` ON `MWC_DOMAIN_PROPERTY` (`DOMAIN_ID` ASC) ;


-- -----------------------------------------------------
-- Table `MWC_SECURITY_QUESTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MWC_SECURITY_QUESTION` ;

CREATE  TABLE IF NOT EXISTS `MWC_SECURITY_QUESTION` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT ,
  `CLIENT_ID` BIGINT NOT NULL ,
  `QUESTION` VARCHAR(100) NULL ,
  `ANSWER` VARCHAR(100) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK1_SECURITY_QUESTION`
    FOREIGN KEY (`CLIENT_ID` )
    REFERENCES `MWC_CLIENT` (`ID` )
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `UK1_SECURITY_QUESTION` ON `MWC_SECURITY_QUESTION` (`CLIENT_ID` ASC, `QUESTION` ASC) ;

CREATE INDEX `FK1_SECURITY_QUESTION` ON `MWC_SECURITY_QUESTION` (`CLIENT_ID` ASC) ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
