INSERT INTO MWC_DOMAIN (NAME) VALUES ('DEFAULT');

INSERT INTO MWC_ROLE (NAME) VALUES ('SYS');
INSERT INTO MWC_ROLE (NAME) VALUES ('ADMIN');
INSERT INTO MWC_ROLE (NAME) VALUES ('MANAGER');
INSERT INTO MWC_ROLE (NAME) VALUES ('USER');